// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mainArea': string;
  'root': string;
  'sidePanel': string;
  'testMainArea': string;
  'testSidePanel': string;
}
export const cssExports: CssExports;
export default cssExports;
